//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public interface IFormula 
{
	object IsConsistent { get;set; }

	void AddClause(IClause clause);

	void RemoveClause();

	void SubstituteAsTrue();

	void SubstituteAsFalse();

}

